Ucitavanje baze:

In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 500)

In [2]:
carvana = pd.read_csv("final_data.csv")
carvana.head()

Unnamed: 0   VehYear  VehicleAge    VehOdo    VNZIP1  VehBCost  \
0           0 -0.191806   -0.106505  0.157568 -0.930981 -1.065435   
1           1 -0.768751    0.475038 -0.401661 -0.930981 -1.523737   
2           2 -0.191806   -0.106505 -0.145604 -0.930981 -1.581025   
3           3 -0.768751    0.475038  0.652406 -0.930981 -0.664420   
4           4 -0.768751    0.475038  0.319123 -0.930981  1.168791   

   IsOnlineSale  WarrantyCost  PurchYear  AcquisitionAuctionRatio  \
0     -0.166793      0.194455  -1.031687                -2.244656   
1     -0.166793     -1.075463  -1.031687                -1.707170   
2     -0.166793     -0.422936  -1.031687                -0.684055   
3     -0.166793     -1.135696  -1.031687                -0.367682   
4     -0.166793     -0.590250  -1.031687                -0.352668   

   AcquisitionRetailRatio  CurrentAuctionRatio  CurrentRetailRatio  \
0               -0.629052            -1.410765           -0.681319   
1               -0.674570            -1.864448           -1.236092   
2                0.650894            -1.184988           -0.080909   
3               -1.387553            -0.136808            0.122449   
4               -0.375692            -0.242636            0.598443   

   Make_ACURA  Make_BUICK  Make_CADILLAC  Make_CHEVROLET  Make_CHRYSLER  \
0         0.0         0.0            0.0             0.0            0.0   
1         0.0         0.0            0.0             0.0            0.0   
2         0.0         0.0            0.0             0.0            0.0   
3         0.0         0.0            0.0             0.0            0.0   
4         0.0         0.0            0.0             0.0            0.0   

   Make_DODGE  Make_FORD  Make_GMC  Make_HONDA  Make_HUMMER  Make_HYUNDAI  \
0         1.0        0.0       0.0         0.0          0.0           0.0   
1         1.0        0.0       0.0         0.0          0.0           0.0   
2         0.0        1.0       0.0         0.0          0.0           0.0   
3         0.0        0.0       0.0         0.0          0.0           0.0   
4         1.0        0.0       0.0         0.0          0.0           0.0   

   Make_INFINITI  Make_ISUZU  Make_JEEP  Make_KIA  Make_LEXUS  Make_LINCOLN  \
0            0.0         0.0        0.0       0.0         0.0           0.0   
1            0.0         0.0        0.0       0.0         0.0           0.0   
2            0.0         0.0        0.0       0.0         0.0           0.0   
3            0.0         0.0        0.0       0.0         0.0           0.0   
4            0.0         0.0        0.0       0.0         0.0           0.0   

   Make_MAZDA  Make_MERCURY  Make_MINI  Make_MITSUBISHI  Make_NISSAN  \
0         0.0           0.0        0.0              0.0          0.0   
1         0.0           0.0        0.0              0.0          0.0   
2         0.0           0.0        0.0              0.0          0.0   
3         0.0           0.0        0.0              1.0          0.0   
4         0.0           0.0        0.0              0.0          0.0   

   Make_OLDSMOBILE  Make_PLYMOUTH  Make_PONTIAC  Make_SATURN  Make_SCION  \
0              0.0            0.0           0.0          0.0         0.0   
1              0.0            0.0           0.0          0.0         0.0   
2              0.0            0.0           0.0          0.0         0.0   
3              0.0            0.0           0.0          0.0         0.0   
4              0.0            0.0           0.0          0.0         0.0   

   Make_SUBARU  Make_SUZUKI  Make_TOYOTA  Make_VOLKSWAGEN  Make_VOLVO  \
0          0.0          0.0          0.0              0.0         0.0   
1          0.0          0.0          0.0              0.0         0.0   
2          0.0          0.0          0.0              0.0         0.0   
3          0.0          0.0          0.0              0.0         0.0   
4          0.0          0.0          0.0              0.0         0.0   

   Color_BEIGE  Color_BLACK  Color

In [3]:
X = carvana.drop(["Unnamed: 0", "IsBadBuy"], axis = 1)
y = carvana['IsBadBuy']

F-ja za izracunavanje evaluacionih metrika:

In [4]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, roc_auc_score

def print_performance(y, y_pred):
    print(f'Accuracy : {accuracy_score(y, y_pred)}')
    print(f'Precision : {precision_score(y, y_pred)}')
    print(f'Recall : {recall_score(y, y_pred)}')
    print(f'F1 : {f1_score(y, y_pred)}')

Podelimo podatke u train i test:

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2019)

# KREIRANJE MODELA

#### STABLO ODLUCIVANJA

Napravimo model stabla odlucivanja sa default parametrima:

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)

DecisionTreeClassifier()

Auc na train delu:

In [7]:
cross_val_score(tree ,X_train, y_train, cv = 10, scoring="roc_auc").mean()

0.5260300065032719

Kreirajmo predikcije i matricu konfuzije na test delu:

In [8]:
y_pred_tree = tree.predict_proba(X_test)[:, 1] > 0.1
confusion_matrix(y_test, y_pred_tree)

array([[1515,  250],
       [ 232,   43]], dtype=int64)

Izracunajmo i prikazimo standardne evaluacione metrike:

In [9]:
print_performance(y_test, y_pred_tree)

Accuracy : 0.7637254901960784
Precision : 0.14675767918088736
Recall : 0.15636363636363637
F1 : 0.15140845070422537


Auc na test delu:

In [10]:
roc_auc_score(y_test, y_pred_tree)

0.5073602884367756

#### LOGISTICKA REGRESIJA

Kreirajmo model logisticke regresije sa default parametrima:

In [11]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(solver="liblinear")
lr.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

Auc na train delu:

In [12]:
cross_val_score(lr, X_train, y_train, cv = 10, scoring="roc_auc").mean()

0.6759452661143575

Kreirajmo predikcije i matricu konfuzije na test delu:

In [13]:
y_pred_lr = lr.predict_proba(X_test)[:, 1] >= 0.1
confusion_matrix(y_test, y_pred_lr)

array([[923, 842],
       [ 79, 196]], dtype=int64)

Sracunajmo i ispisimo standardne evaluacione metrike:

In [14]:
print_performance(y_test, y_pred_lr)

Accuracy : 0.5485294117647059
Precision : 0.18882466281310212
Recall : 0.7127272727272728
F1 : 0.2985529322162985


Auc na test delu:

In [15]:
roc_auc_score(y_test, y_pred_lr)

0.6178367241823333

#### KNN

Kreirajmo model KNN sa default hiperparametrima:

In [16]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

Auc na train-u:

In [17]:
cross_val_score(knn, X_train, y_train, cv = 10, scoring = 'roc_auc').mean()

0.5792606385067957

Kreirajmo predikcije i matricu konfuzije na test setu:

In [18]:
y_pred_knn = knn.predict_proba(X_test)[:, 1] >= 0.1
confusion_matrix(y_test, y_pred_knn)

array([[989, 776],
       [126, 149]], dtype=int64)

Sracunajmo i odstampajmo standardne evaluacione metrike:

In [19]:
print_performance(y_test, y_pred_knn)

Accuracy : 0.557843137254902
Precision : 0.16108108108108107
Recall : 0.5418181818181819
F1 : 0.24833333333333332


Auc na test delu:

In [20]:
roc_auc_score(y_test, y_pred_knn)

0.5510790625804791

#### VOTING

Kreirajmo VotingClassifier sa default hiperparametrima algoritama koji glasaju:

In [21]:
from sklearn.ensemble import VotingClassifier

model_voting = VotingClassifier(voting = "soft", estimators=[('lr', lr), ('tree', tree), ('knn', knn)])

model_voting.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(solver='liblinear')),
                             ('tree', DecisionTreeClassifier()),
                             ('knn', KNeighborsClassifier())],
                 voting='soft')

Auc na train delu:

In [22]:
cross_val_score(model_voting, X_train, y_train, cv=10, scoring='roc_auc').mean()

0.6323662281061722

Kreirajmo predikcije i matricu konfuzije:

In [23]:
y_pred_voting = model_voting.predict_proba(X_test)[:,1] > 0.1
confusion_matrix(y_test, y_pred_voting)

array([[1077,  688],
       [ 131,  144]], dtype=int64)

In [35]:
print_performance(y_test, y_pred_voting)

Accuracy : 0.5985294117647059
Precision : 0.17307692307692307
Recall : 0.5236363636363637
F1 : 0.26016260162601623


Auc na test delu:

In [24]:
roc_auc_score(y_test, y_pred_voting)

0.5669173319598249

#### STACKING

Kreirajmo StackingClassifier sa difoltnim hiperparametrima algoritama koji glasaju:

In [25]:
from mlxtend.classifier import StackingClassifier
model_stacking = StackingClassifier(classifiers = [lr, tree],
                                   meta_classifier = lr,
                                   use_features_in_secondary=True)
model_stacking.fit(X_train, y_train)

StackingClassifier(classifiers=[LogisticRegression(solver='liblinear'),
                                DecisionTreeClassifier()],
                   meta_classifier=LogisticRegression(solver='liblinear'),
                   use_features_in_secondary=True)

Auc na train delu:

In [26]:
cross_val_score(model_stacking, X_train, y_train, cv=10, scoring='roc_auc').mean()

0.6426524316726542

Kreirajmo predikcije i matricu konfuzije:

In [27]:
y_pred_stacking = model_stacking.predict_proba(X_test)[:,1] > 0.1
confusion_matrix(y_test, y_pred_stacking)

array([[1516,  249],
       [ 238,   37]], dtype=int64)

Sracunajmo osnovne evaluacione metrike iz matrice konfuzije:

In [28]:
print_performance(y_test, y_pred_stacking)

Accuracy : 0.7612745098039215
Precision : 0.12937062937062938
Recall : 0.13454545454545455
F1 : 0.13190730837789663


Auc na test delu:

In [29]:
roc_auc_score(y_test, y_pred_stacking)

0.496734483646665

#### BAGGING

In [30]:
from sklearn.ensemble import BaggingClassifier
model_bagging = BaggingClassifier(base_estimator = lr, bootstrap=100)
model_bagging.fit(X_train, y_train)

BaggingClassifier(base_estimator=LogisticRegression(solver='liblinear'),
                  bootstrap=100)

Auc na train delu:

In [31]:
cross_val_score(model_bagging, X_train, y_train, cv=10, scoring='roc_auc').mean()

0.6717804626898222

Kreirajmo predikcije i matricu konfuzije na test delu:

In [32]:
y_pred_bagging = model_bagging.predict_proba(X_test)[:, 1] > 0.1
confusion_matrix(y_test, y_pred_bagging)

array([[926, 839],
       [ 78, 197]], dtype=int64)

Sracunajmo i ispisimo standardne evaluacione metrike:

In [33]:
print_performance(y_test, y_pred_bagging)

Accuracy : 0.5504901960784314
Precision : 0.19015444015444016
Recall : 0.7163636363636363
F1 : 0.30053394355453855


Auc na test delu:

In [34]:
roc_auc_score(y_test, y_pred_bagging)

0.6205047643574555